### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [fe80/fe80.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by fe80** [comment]
Hello @unixorn,

I'm sorry I never see this issue, I added an Apache v2 license https://github.com/fe80/fe80.zsh-theme/commit/b345ab161e7771eef5774845f086060d1ec48b05

**Comment by unixorn** [comment]
Thanks, adding it today.
